#ifndef STATE_H
#define STATE_H

enum state
{
    STATE_BEGIN,
    STATE_VERSION,
    STATE_VERSION_NL,
    STATE_REGION_NAME,
    STATE_REGION_START,
    STATE_REGION_END,
    STATE_REGION_NL,
    STATE_FEAT_SOURCE,
    STATE_FEAT_TYPE,
    STATE_FEAT_START,
    STATE_FEAT_END,
    STATE_FEAT_SCORE,
    STATE_FEAT_STRAND,
    STATE_FEAT_PHASE,
    STATE_FEAT_ATTRS,
    STATE_FEAT_NL,
    STATE_PAUSE,
    STATE_END,
    STATE_ERROR
};

#endif
